# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meistrai_app', '0002_auto_20170123_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='title',
            field=models.CharField(default='Titulas', max_length=100, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
